
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "code.cloudfoundry.org/commandrunner"

[[constraint]]
  name = "github.com/JulzDiverse/goml"

[[constraint]]
  name = "github.com/JulzDiverse/mingoak"

[[constraint]]
  name = "github.com/JulzDiverse/osenv"

[[constraint]]
  name = "github.com/cppforlife/go-patch"

[[constraint]]
  name = "github.com/geofffranks/simpleyaml"

[[constraint]]
  name = "github.com/geofffranks/spruce"

[[constraint]]
  name = "github.com/onsi/ginkgo"

[[constraint]]
  name = "github.com/onsi/gomega"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/starkandwayne/goutils"

[[constraint]]
  name = "github.com/urfave/cli"

[[constraint]]
  name = "gopkg.in/yaml.v2"
